[build]
  command = "yarn run build"
  publish = "/public"


[context.deploy-preview]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_ENV = "production" }
  base = "/"
  preview_path = "/preview"