# netlify.toml

[build]
  command = "yarn build"
  base = "docs"
  publish = "docs"
  preview_path = "/dist/{{build_id}}"

[context.deploy-preview]
  command = "yarn build"
  publish = "/dist"

  


    


