[build]
  command = "npm run build"
  publish = "dist"


[context.deploy-preview]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_ENV = "production" }
  base = "/"
  preview_path = "https://hitowa-test-cms.netlify.app/preview"


