[build]
  command = "yarn run build"
  publish = "/public"


[context.deploy-preview]
  command = "yarn run docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_ENV = "mster" }
  base = "/"
  preview_path = "https://hitowa-test-cms.netlify.app/preview"


