[[workflow.trigger]]
  name = "preview-link"
  on = "draft"
  publish = "preview-build"
  jobs = [
    {
      command = "yarn build-preview"
    },
    {
      command = "yarn send-preview-email"
    }
  ]