
# netlify.toml

[build]
  publish = "/docs"
  preview_path = "/dist/docs/{{build_id}}"

[context.deploy-preview]
  command = "yarn build"
  publish = "/dist/docs"

[[context.deploy-preview.environment]]
  REACT_APP_API_URL = "https://preview-api.example.com"

[context.preview]
  command = "npm run build:preview"
  preview_path = "/dist/docs{{build_id}}"

[[context.preview.environment]]
  REACT_APP_API_URL = "https://preview-api.example.com"

    


