# netlify.toml

[build]
  base = "src"
  publish = "/dist"
  preview_path = "/dist/{{build_id}}"

[context.deploy-preview]
  command = "yarn run build"

[[context.deploy-preview.environment]]
  REACT_APP_API_URL = "https://preview-api.example.com"



    


