backend:
  name: git-gateway
  branch: master
media_folder: "images/"
display_url: https://hitowa-test-cms.netlify.app
collections:
  - name: pages
    label: Pages
    folder: "docs"
    create: true
    slug: "{{slug}}"
    autoFilename: true
    defaultOperations: '/resize/800x600/'
    editor:
      preview: true

    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Link",name: "Link",widget: "string"}
      - {label: Full_image, name: full_image, widget: image}
      - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}

      - name: sections
        widget: list
        types:
          - name: text_section
            label: Text
            widget: object
            folder: "docs"
            slug: "{{slug}}"
            create: true
            fields: 
              - {label: "Body", name: "body", widget: "markdown"}

          - name: image_section
            label: Image
            widget: object
            folder: "docs"
            slug: "{{slug}}"
            create: true
            fields: 
              - {name: image, widget: image}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}


          - name: slider_section
            label: Slider
            widget: object
            folder: "docs"
            slug: "{{slug}}"
            create: true
            preview: true
            fields:
              - name: images  
                widget: list
                field: {label: Image, name: image, widget: image}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}

          - name: video_section
            label: Video
            widget: object
            folder: "docs"
            slug: "{{slug}}"
            create: true
            fields:
              - {name: embed, label: Embed video, hint: 'YouTube or Vimeo url'}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}