backend:
  name: git-gateway
  branch: master
media_folder: "/images/"
display_url: https://hitowa-test-cms.netlify.app
- name: 'work'
    label: 'Works'
    label_singular: 'Work'
    folder: '_work'
    preview_path: '/work/{{slug}}'  // this works
    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      