backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow 
media_folder: "/images/"
preview_context: deploy-preview
locale: ja
show_preview_links: true 
display_url: https://hitowa-test-cms.netlify.app

collections:
  - name: pages
    label: Pages
    folder: "docs"
    create: true
    identifier_field: title
    preview_path: content/pages{{year}}/{{month}}/{{title}}
    autoFilename: true
    defaultOperations: '/resize/800x600/'
    editor:
      preview: true



      collections:
  - name: blog
    folder: content/blog
    slug: {{year}}-{{month}}-{{slug}}
    preview_path: blog/{{slug}}

    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      