backend:
  name: git-gateway
  branch: master
media_folder: "/images/"
display_url: https://hitowa-test-cms.netlify.app
collections:
    - label: 'Pages'
      name: 'pages'
      label_singular: 'Page'
      folder: 'docs'
      create: true
      format: 'json'
      show_preview_links: true
      nested:
        depth: 100 # max depth to show in the collection tree
        summary: '{{meta}}' # optional summary for a tree node, defaults to the inferred title field
      editor:
        preview: false
    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      