backend:
  name: git-gateway
  branch: master
  preview_context: deploy-preview
publish_mode: editorial_workflow 
media_folder: "/images/"
locale: ja
show_preview_links: true 
display_url: https://hitowa-test-cms.netlify.app

collections:
  - name: pages
    label: Pages
    folder: "docs"
    create: true
    slug: "{{permalink}}"
    #slug: "{{slug}}"
    #preview_path: "blog{{year}}/{{month}}/{{slug}}"
    preview_path: "/dist{{year}}/{{month}}/{{slug}}"
    identifier_field: postTitle
    autoFilename: true
    defaultOperations: '/resize/800x600/'
    editor:
      preview: fase

    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      