backend:
  name: git-gateway
  branch: origin
publish_mode: editorial_workflow 
media_folder: "/images/"
preview_context: deploy-preview
locale: ja
show_preview_links: true 
display_url: https://hitowa-test-cms.netlify.app

collections:
  - name: pages
    folder: content/docs
    slug: {{year}}-{{month}}-{{slug}}
    preview_path: 'dist/{date}/{title}',
    create: true,
    editor:
      preview: true
    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      