backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow 
media_folder: "/images/"
preview_context: deploy-preview
workflow:
  name: Preview
  trigger:
    - create
    - delete
    - update
  rules:
    - match: path
      pattern: '*/pages/*'
      value: 'published'
      path: 'status'
      action: 'create'
  actions:
    - create_preview:
        publish: true
        roles:
          - editor
    - create_deploy_preview:
        roles:
          - editor
    - delete_preview:
        roles:
          - editor
locale: ja
show_preview_links: true 
display_url: https://hitowa-test-cms.netlify.app

collections:
  - name: pages
    label: Pages
    folder: docs
    create: true
    slug: {{year}}-{{month}}-{{slug}}
    autoFilename: true
    preview_path: docs/{{year}}/{{month}}/{{title}}.html
    defaultperations: '/resize/800x600/'
    editor:
      preview: true
    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      
