backend:
  name: git-gateway
  branch: master
media_folder: "/images/"
display_url: https://hitowa-test-cms.netlify.app
collections:
#   - name: pages
#     label: Pages
#     folder: "docs"
#     create: true
#     preview_path: "docs{{slug}}"
#     autoFilename: true
#     defaultOperations: '/resize/800x600/'
#     show_preview_links: true
#     editor:
#       preview: true
- name: 'pages'
    label: 'pages'
    label_singular: 'pages'
    folder: 'docs'
    preview_path: 'docs{{slug}}' 


    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      