backend:
  name: git-gateway
  branch: master
media_folder: ".vuepress/public/"
public_folder: "../../"
display_url: lustrous-madeleine-671076.netlify.app
collections:
  - name: pages
    label: Pages
    folder: "/hitowa/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true

    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}

  - name: sections
    widget: list
    types:
  - name: text_section
    label: Text
    widget: object
    folder: "/hitowa/"
    slug: "{{slug}}"
    create: true
    editor:
    preview: true

    fields: 
      - {label: "Body", name: "body", widget: "markdown"}

         